### ISSUE TITLE
core-js won't build with Node 14

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-js#577]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

With Node 12, I can build core-js properly but when I switch with `nvm` to Node 14, the build process fails:

```yarn && yarn build

yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/4] ⡀ node-lmdb
[-/4] ⡀ waiting...
[-/4] ⢀ waiting...
error /home/stefan/code/node/core-js/node_modules/node-lmdb: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/stefan/code/node/core-js/node_modules/node-lmdb
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.0 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/stefan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/code/node/core-js/node_modules/node-lmdb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/.cache/node-gyp/14.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/stefan/.cache/node-gyp/14.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/stefan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/stefan/.cache/node-gyp/14.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/stefan/code/node/core-js/node_modules/node-lmdb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/stefan/code/node/core-js/node_modules/node-lmdb/build'
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
  CXX(target) Release/obj.target/node-lmdb/src/env.o
../src/env.cpp: In constructor ‘BatchWorker::BatchWorker(MDB_env*, action_t*, int, int, Nan::Callback*, Nan::Callback*)’:
../src/env.cpp:269:15: warning: ‘BatchWorker::actions’ will be initialized after [-Wreorder]
     action_t* actions;
               ^~~~~~~
../src/env.cpp:265:9: warning:   ‘int BatchWorker::actionCount’ [-Wreorder]
     int actionCount;
         ^~~~~~~~~~~
../src/env.cpp:137:5: warning:   when initialized here [-Wreorder]
     BatchWorker(MDB_env* env, action_t *actions, int actionCount, int putFlags, Nan::Callback *callback, Nan::Callback *progress)
     ^~~~~~~~~~~
../src/env.cpp:270:9: warning: ‘BatchWorker::putFlags’ will be initialized after [-Wreorder]
     int putFlags;
         ^~~~~~~~
../src/env.cpp:264:14: warning:   ‘MDB_env* BatchWorker::env’ [-Wreorder]
     MDB_env* env;
              ^~~
../src/env.cpp:137:5: warning:   when initialized here [-Wreorder]
     BatchWorker(MDB_env* env, action_t *actions, int actionCount, int putFlags, Nan::Callback *callback, Nan::Callback *progress)
     ^~~~~~~~~~~
../src/env.cpp: In member function ‘virtual void BatchWorker::Execute(const Nan::AsyncBareProgressWorker<char>::ExecutionProgress&)’:
../src/env.cpp:166:13: warning: unused variable ‘getCount’ [-Wunused-variable]
         int getCount = 0;
             ^~~~~~~~
../src/env.cpp: In member function ‘v8::Local<v8::Array> BatchWorker::updatedResultsArray(int)’:
../src/env.cpp:239:91: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
             resultsArray->Set(context, resultIndex, Nan::New<Number>(results[resultIndex]));
                                                                                           ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::stat(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:401:101: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("pageSize").ToLocalChecked(), Nan::New<Number>(stat.ms_psize));
                                                                                                     ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:402:102: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("treeDepth").ToLocalChecked(), Nan::New<Number>(stat.ms_depth));
                                                                                                      ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:403:119: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("treeBranchPageCount").ToLocalChecked(), Nan::New<Number>(stat.ms_branch_pages));
                                                                                                                       ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:404:115: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("treeLeafPageCount").ToLocalChecked(), Nan::New<Number>(stat.ms_leaf_pages));
                                                                                                                   ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:405:105: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("entryCount").ToLocalChecked(), Nan::New<Number>(stat.ms_entries));
                                                                                                         ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::info(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:429:119: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("mapAddress").ToLocalChecked(), Nan::New<Number>((uint64_t) envinfo.me_mapaddr));
                                                                                                                       ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:430:105: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("mapSize").ToLocalChecked(), Nan::New<Number>(envinfo.me_mapsize));
                                                                                                         ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:431:114: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("lastPageNumber").ToLocalChecked(), Nan::New<Number>(envinfo.me_last_pgno));
                                                                                                                  ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:432:110: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("lastTxnId").ToLocalChecked(), Nan::New<Number>(envinfo.me_last_txnid));
                                                                                                              ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:433:111: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("maxReaders").ToLocalChecked(), Nan::New<Number>(envinfo.me_maxreaders));
                                                                                                               ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp:434:111: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     obj->Set(context, Nan::New<String>("numReaders").ToLocalChecked(), Nan::New<Number>(envinfo.me_numreaders));
                                                                                                               ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp: In static member function ‘static void EnvWrap::setupExports(v8::Local<v8::Object>)’:
../src/env.cpp:694:148: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     exports->Set(Nan::GetCurrentContext(), Nan::New<String>("Env").ToLocalChecked(), envTpl->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
                                                                                                                                                    ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::batchWrite(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:563:35: warning: ‘keyType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         action->freeKey = argToKey(key, action->key, keyType, keyIsValid);
                           ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/node-lmdb/src/misc.o
../src/misc.cpp:285:11: warning: extra tokens at end of #endif directive [-Wendif-labels]
     #endif;
           ^
../src/misc.cpp: In function ‘void setupExportMisc(v8::Local<v8::Object>)’:
../src/misc.cpp:34:120: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     versionObj->Set(context, Nan::New<String>("versionString").ToLocalChecked(), Nan::New<String>(str).ToLocalChecked());
                                                                                                                        ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/misc.cpp:35:98: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     versionObj->Set(context, Nan::New<String>("major").ToLocalChecked(), Nan::New<Integer>(major));
                                                                                                  ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/misc.cpp:36:98: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     versionObj->Set(context, Nan::New<String>("minor").ToLocalChecked(), Nan::New<Integer>(minor));
                                                                                                  ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/misc.cpp:37:98: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     versionObj->Set(context, Nan::New<String>("patch").ToLocalChecked(), Nan::New<Integer>(patch));
                                                                                                  ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/misc.cpp:39:83: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     exports->Set(context, Nan::New<String>("version").ToLocalChecked(), versionObj);
                                                                                   ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
../src/misc.cpp: In function ‘void setFlagFromValue(int*, int, const char*, bool, v8::Local<v8::Object>)’:
../src/misc.cpp:45:53: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>&)’
     if (opt->IsBoolean() ? opt->BooleanValue(context).ToChecked() : defaultValue) {
                                                     ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:2858:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:2858:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
../src/misc.cpp: In function ‘void throwLmdbError(int)’:
../src/misc.cpp:249:100: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
     err.As<Object>()->Set(Nan::GetCurrentContext(), Nan::New("code").ToLocalChecked(), Nan::New(rc));
                                                                                                    ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/misc.cpp:24:
/home/stefan/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
node-lmdb.target.mk:137: recipe for target 'Release/obj.target/node-lmdb/src/misc.o' failed
make: Leaving directory '/home/stefan/code/node/core-js/node_modules/node-lmdb/build'
make: *** [Release/obj.target/node-lmdb/src/misc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/stefan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-58-generic
gyp ERR! command "/home/stefan/.nvm/versions/node/v14.15.0/bin/node" "/home/stefan/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stefan/code/node/core-js/node_modules/node-lmdb
gyp ERR! node -v v14.15.0```

**Comment by Eligioo** [comment]
Didn't find any issues regarding this problem but noticed an open PR (#573) afterwards.
